// Generated by https://quicktype.io

export interface productos {
    id_producto?:          number;
    nombre_producto?:      string;
    descripcion_producto?: string;
    precio_producto?:      number;
    imagen_producto?:      String;
    nombre_categoria?:     number;
}

export interface User {
    id_usuario: number;
    usuario:    string;
    correo:     string;
    contrasena: string;
    rol:        number;
}
