// Generated by https://quicktype.io

export interface productos {
    id?:                   number;
    nombre_producto?:      string;
    descripcion_producto?: string;
    precio_producto?:      number;
    imagen_producto?:      String;
    nombre_categoria?:     number;
}
